Create caro_speaking.md
meilisearch/devrel pull request #203
Opened 2021-02-23 20:46 UTC by CaroFG

2021-02-24 16:59 UTC, fharper reviewed
Can you also create a speaking.md page, with a link to this markdown, and add my name also and point to https://fred.dev/speaking please.

Also, add a link in the main index "Speaking" that point to the page I just told you about :D

2021-02-24 16:59 UTC, fharper commented on caro_speaking.md
> + - Back to the living room hackathon (05/02/2021)
Add a link to the event

2021-02-24 16:59 UTC, fharper commented on caro_speaking.md
> + - Rawkode Live (16/02/2021)
add a link to his YouTube channel

2021-02-25 19:24 UTC, fharper requested changes
> Can you also create a speaking.md page, with a link to this markdown, and add my name also and point to https://fred.dev/speaking please.
> 
> Also, add a link in the main index "Speaking" that point to the page I just told you about :D

You are missing this one :)

2021-03-01 09:19 UTC, CaroFG commented
Ok, so just to be sure. You want a speaking.md page with both our names and a link to the caro_speaking.md file and a link to your website. Is it correct? Should we put all those files in a folder?

2021-03-01 18:48 UTC, fharper commented
Haha, I'll make the changes, will be simpler :)

2021-03-01 20:23 UTC, fharper approved these changes
LGTM

2021-03-01 20:23 UTC, merged