Companies mentions and love
meilisearch/devrel pull request #250
Opened 2021-03-25 20:23 UTC by CaroFG

2021-03-25 20:24 UTC, CaroFG commented
Not sure where to put the links to those files, in the assets readme or in the main readme?

2021-03-29 18:13 UTC, fharper reviewed
> Not sure where to put the links to those files, in the assets readme or in the main readme?

In the asset README.

2021-03-29 18:13 UTC, fharper commented on assets/companies.md
> +# Companies using MeiliSearch
Compagnies & Organizations?

2021-03-29 18:13 UTC, fharper commented on assets/companies.md
> +| [Platform.sh](https://docs.platform.sh/) | Platform-as-a-Service built especially for continuous deployment |	Cross-site search  | [tweet](https://twitter.com/robertDouglass/status/1262395403363921
Can you order ASC by companies please

2021-03-29 18:13 UTC, fharper commented on assets/meili-love.md
> +# Love from our users
Can you put the text of the tweets, and date please (link the text to the link you added here). Order them by date ASC please :D

2021-03-29 18:13 UTC, fharper commented on assets/mentions.md
> +# Mentions of MeiliSearch
Put the date, order them by ASC date.

Link to the date so links are hidden instead of a list of links.

2021-03-30 10:24 UTC, CaroFG commented
Fixes #204

2021-03-30 13:24 UTC, fharper requested changes

2021-03-30 13:24 UTC, fharper commented on assets/meili-love.md
> +- 20/03/2020: [love the performance and simplicity of MeiliSearch](https://github.com/meilisearch/MeiliSearch/issues/535#issue-585176606)
My bad, I should have mention it, but can you put the date YYYY-MM-DD :D

It make more sense when you order by date ASC 😬

2021-03-30 13:24 UTC, fharper commented on assets/mentions.md
> +# Mentions of MeiliSearch
Same for date here 😬

2021-03-30 15:41 UTC, merged