Update mentions.md
meilisearch/devrel pull request #264
Opened 2021-05-06 13:42 UTC by CaroFG

2021-05-06 14:42 UTC, tpayet approved these changes

2021-05-09 14:04 UTC, bidoubiwa commented on assets/mentions.md
> +[2021/05/03](http://www.skrejci.com/2021/05/meilisearch-under-windows/) | "MeiliSearch under Windows"
```suggestion
[2021/05/07](https://blog.simonireilly.com/posts/serverless-search) | "https://blog.simonireilly.com/posts/serverless-search"

```

2021-05-09 14:04 UTC, bidoubiwa requested changes
Just a little addition 🔥

2021-05-09 14:04 UTC, bidoubiwa commented on assets/mentions.md
> +[2021/05/03](http://www.skrejci.com/2021/05/meilisearch-under-windows/) | "MeiliSearch under Windows"
```suggestion
[2021/05/03](http://www.skrejci.com/2021/05/meilisearch-under-windows/) | "MeiliSearch under Windows"
[2021/05/07](https://blog.simonireilly.com/posts/serverless-search) | "Serverless search with Meilisearch and Google Cloud Run"
```

2021-05-10 07:19 UTC, merged